#Login
app_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: AppBundle:Template:index.html.twig
app_login:
    path: /login/
    defaults: { _controller: 'AppBundle:Auth:login' }
app_login_check:
    path: /login_check
app_security_logout:
    path: /logout
app_register:
    path: /register
    defaults: { _controller: 'AppBundle:Register:index' }
app_register_notification:
    path: /register/notification
    defaults: { _controller: 'AppBundle:Register:notification' }
app_forgot:
    path: /forgot
    defaults: { _controller: 'AppBundle:Register:forgot' }
app_forgotcomfirm:
    path: /forgotcomfirm
    defaults: { _controller: 'AppBundle:Register:forgotcomfirm' }